spring.application.name=order-service
server.port=8080

# Base de données H2 en mémoire (pour commencer)
spring.datasource.url=jdbc:h2:mem:ordersdb
spring.jpa.hibernate.ddl-auto=update

# Kafka
spring.kafka.bootstrap-servers=kubeflux-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
jwt.secret=kubeflux-super-secret-key-change-in-production-min-32-chars